project_id = "cha-de-bebe-manoel"

[api]
enabled = true
schemas = ["public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[auth]
enabled = true
site_url = "http://localhost:3000"
additional_redirect_urls = ["https://seu-usuario.github.io/cha-de-bebe-manoel/"]

[db]
major_version = 15
