project_id = "cha-de-bebe-do-manoel"

[api]
enabled = true
schemas = ["public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[auth]
enabled = true
site_url = "https://sharalutke.github.io/cha-de-bebe-do-manoel/"
additional_redirect_urls = ["http://localhost:3000/cha-de-bebe-do-manoel/", "https://sharalutke.github.io/cha-de-bebe-do-manoel/"]

[db]
major_version = 15
